basePath: /api/v1
info:
  contact: {}
paths:
  /urls:
    get:
      consumes:
      - application/json
      description: Query the database and forward all URL pairs to the requester
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: url
      summary: Get all URL pairs
      tags:
      - GET
swagger: "2.0"
